# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_date', models.DateField()),
                ('blog_descr', models.TextField()),
                ('blog_author', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_descr',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
