# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 08:01
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170909_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_text',
            field=tinymce.models.HTMLField(default='Nothing to show!'),
        ),
    ]
