# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 09:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_descr',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
