# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 09:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171029_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_descr',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
