# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 09:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171029_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
